name: Deploy PR
on:
  pull_request:
    types: [opened, synchronize, reopened]

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployPR:
    runs-on: ubuntu-latest
    # env:
    #Define your envs needed for static generation:
    # ENV_NAME: ${{ secrets.ENV_NAME }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125605859:role/GitHubSstDeployer
          role-duration-seconds: 900 #adjust as needed for your build time
          aws-region: us-east-1
      - name: Install dependencies
        run: npm i
      - name: Deploy app
        run: |
          DEPLOY_OUTPUT="$(npx sst deploy --stage pr-${{ github.event.number }})"
          echo "$DEPLOY_OUTPUT"
          PREVIEW_URL=$(echo "$DEPLOY_OUTPUT" | grep -o 'http[s]://[^ ]*')  # assuming the URL starts with http(s) and ends with a space
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            "Deployed app can be previewed at ${{env.PREVIEW_URL}}"
